name: roboshop Update

on:
  schedule:
    - cron: '0 5 * * MON'  # Every Monday at 5 AM UTC
  workflow_dispatch:

jobs:
  keep-active:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create timestamp
        run: |
          echo "Last update: $(date -u)" > weekly-update.txt

      - name: Commit and push
        run: |
          git config user.name "activity-bot"
          git config user.email "bot@example.com"
          git add weekly-update.txt
          git commit -m "Automated update - $(date -u)" || echo "No changes to commit"
          git push
